# Sidebar navigation

- label: 'Общая информация'
  link: '/azurion'
- label: 'Королевства Триумвирата'
  link: '/azurion/locations/triumvirat'
- label: 'Расы'
  items:
    - label: 'Расы Азуриона'
      link: '/azurion/races/main'
    - label: 'Дженази'
      link: '/azurion/races/genasi'
- label: 'Дополнительные классы'
  items:
    - label: 'Воин / Рунический рыцарь'
      link: /azurion/classes/fighter.rune-knight
    - label: 'Друид / Круг Спор'
      link: /azurion/classes/druid.circle-spores
    - label: 'Жрец / Домен смерти'
      link: /azurion/classes/cleric.death
    - label: 'Паладин / Клятвопреступник'
      link: /azurion/classes/paladin.oathbreaker
    - label: 'Плут / Божественный вестник'
      link: /azurion/classes/rogue.divine
    - label: 'Колдун / Бессмертный'
      link: /azurion/classes/warlock.undying
    - label: 'Магия вуду'
      link: /azurion/classes/woodoo
- label: 'Предыстории'
  items:
    - label: 'Воскрешённый'
      link: /azurion/backstories/resurrected
    - label: 'Еретик'
      link: /azurion/backstories/heretic