# Sidebar navigation

- label: 'Общая информация'
  link: '/'
- label: 'Королевства Триумвирата'
  link: '/locations/triumvirat'
- label: 'Расы'
  items:
    - label: 'Расы Азуриона'
      link: '/races/main'
    - label: 'Изменения в расах'
      link: '/races/race-changes'
- label: 'Дополнительные классы'
  items:
    - label: 'Друид / Круг Спор'
      link: /classes/circle-spores-druid
    - label: 'Плут / Божественный вестник'
      link: /classes/divine-rogue
