# Sidebar navigation

- label: 'Общая информация'
  link: '/azurion'
- label: 'Локации'
  items:
    - label: 'Королевства Триумвирата'
      link: '/azurion/locations/triumvirat'
    - label: 'Вольный порт Илсар'
      link: '/azurion/locations/ilsar'
    - label: 'Государство Гвендалар'
      link: '/azurion/locations/gwendalar'
    - label: 'Архипелаг Огненные Клыки'
      link: '/azurion/locations/fire-fangs'
- label: 'Расы'
  items:
    - label: 'Расы Азуриона'
      link: '/azurion/races/main'
    - label: '[ОК] Грунг'
      link: '/azurion/races/grung'
    - label: '[ОК] Себекканин'
      link: '/azurion/races/sebekkan'
    - label: 'Дженази'
      link: '/azurion/races/genasi'
    - label: 'Оборотень'
      link: '/azurion/races/shifter'
    - label: 'Кобольд'
      link: '/azurion/races/kobold'
    - label: 'Многоликий'
      link: '/azurion/races/changeling'
- label: 'Дополнительные классы'
  items:
    - label: 'Воин / Рунический рыцарь'
      link: /azurion/classes/fighter.rune-knight
    - label: 'Волшебник / Песнь клинка'
      link: /azurion/classes/wizard.bladesinger
    - label: 'Друид / Круг Спор'
      link: /azurion/classes/druid.circle-spores
    - label: 'Жрец / Домен смерти'
      link: /azurion/classes/cleric.death
    - label: 'Паладин / Клятвопреступник'
      link: /azurion/classes/paladin.oathbreaker
    - label: 'Плут / Божественный вестник'
      link: /azurion/classes/rogue.divine
    - label: 'Колдун / Бессмертный'
      link: /azurion/classes/warlock.undying
    - label: 'Колдун / Джинн'
      link: /azurion/classes/warlock.genie
    - label: 'Колдун / Создание Глубин'
      link: /azurion/classes/warlock.lurker
    - label: 'Монах / Путь Милосердия'
      link: /azurion/classes/monk.way-of-mercy
    - label: 'Магия вуду'
      link: /azurion/classes/woodoo
- label: 'Предыстории'
  items:
    - label: 'Воскрешённый'
      link: /azurion/backstories/resurrected
    - label: 'Еретик'
      link: /azurion/backstories/heretic