# Sidebar navigation

- label: 'Общая информация'
  link: '/'
- label: 'Королевства Триумвирата'
  link: '/locations/triumvirat'
- label: 'Расы'
  items:
    - label: 'Расы Азуриона'
      link: '/races/main'
    - label: 'Дженази'
      link: '/races/genasi'
- label: 'Дополнительные классы'
  items:
    - label: 'Воин / Рунический рыцарь'
      link: /classes/fighter.rune-knight
    - label: 'Друид / Круг Спор'
      link: /classes/druid.circle-spores
    - label: 'Жрец / Домен смерти'
      link: /classes/cleric.death
    - label: 'Паладин / Клятвопреступник'
      link: /classes/paladin.oathbreaker
    - label: 'Плут / Божественный вестник'
      link: /classes/rogue.divine
    - label: 'Колдун / Бессмертный'
      link: /classes/warlock.undying
    - label: 'Магия вуду'
      link: /classes/woodoo
